### ISSUE TITLE
Running the playbook issue

### ISSUE THREAD

**Issue by ilhanu** [paritytech/ansible-galaxy#1]
I'm running in to an issue running when trying to set-up a simple polkadot service with the `main.yml` in the node repo
version is  `ansible [core 2.13.2] ansible  [6.2.0] 

The command I'm running is as follows:

`ansible-playbook  roles/node/tasks/main.yml -i ./ansible_hosts.yaml`

**content of ansible_host.yaml**
```yaml
[host1]
192.168.1.11

[host1:vars]
ansible_user=ilhan
node_user=polkadot
node_user_home_path=/home/polkadot
```
Getting the following output:

```
ERROR! 'ansible.builtin.user' is not a valid attribute for a Play

The error appears to be in '/Users/ilhan/devops/ansible-galaxy/roles/node/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Prepare | create user
  ^ here
  ```
  
What is it I'm doing wrong ? 
And it would help a lot of more examples are presented in the README.

**Comment by kogeler** [comment]
Should be fixed. Can you check the last version?

**Comment by ilhanu** [comment]
Still get the same error with the exact same config as written in the issue.  I'm thinking I'm doing something wrong, as this repo is completely different compared to the archived secure-validator-setup. Can you expand the README a bit using an inventory file please, think this can help me out solve it.

**Comment by ddorgan** [comment]
@ilhanu please try calling this role via a playbook.

First add the ansible-galaxy role by creating a `requirements.yaml` with the contents:

```
collections:
  - name: git@github.com:paritytech/ansible-galaxy.git
    type: git
    version: main 
```

Then install the collection using the commands: `mkdir collections ; ansible-galaxy collection install -f -r requirements.yaml -p ./collections`

E.g. create a file called `deploy.yaml` and use:

```
---
- name: deploy node role
  hosts: all
  become: yes
  roles:
    - parity.chain.node 
```

And then run: ` ansible-playbook -i inv.ini deploy.yml` (your inventory is in ini format, not yaml). You may need to include some extra variables like the `node_binary`.

**Comment by ddorgan** [comment]
@ilhanu can you let us know if this helps? If so we can close the issue.

**Comment by ilhanu** [comment]
Hey, Im going to try again in a couple of hours, can you write a small example of the inventory file format complementary to the playbook how it would look like?

**Comment by ddorgan** [comment]
@ilhanu I have put an example [inventory](https://gist.github.com/ddorgan/5520fb8cb54338106399cb3f563bda34) in gist and will open an issue to create a node inventory example in this repo.

**Comment by ilhanu** [comment]
Hey @ddorgan the examples they really made the difference. I was able to create my-chain example on a LAN server.  Some things to note and questions I have after this process.  

- The ini format complains for me, changing it to .yaml was fine, also the [docs](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html) show the format of your inventory stated in yaml. I got this error when running it in `.ini`
```
[WARNING]:  * Failed to parse /Users/ilhan/devops/inventories/try.ini with ini plugin: Invalid host pattern 'all:' supplied, ending in ':' is not allowed, this character
is reserved to provide a port.
[WARNING]: Unable to parse /Users/ilhan/devops/inventories/try.ini as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
```

- When installing it with the method of defined folder -->  `mkdir collections ; ansible-galaxy collection install -f -r requirements.yaml -p ./collections` it generates an `ansible_collections` folder with a very similar output as this repo. But ansible doesn't recognize this as a loaded, how do you run from this specific installed collection in a directory ? 

How I got to do it was without the specified folder: `ansible-galaxy install -f -r requirements.yml`

It loads in the default path of ansible-galaxy collection:

```
# /Users/ilhan/.ansible/collections/ansible_collections
Collection   Version
------------ -------
parity.chain 1.0.1
```

I'll dig a bit deeper now how the chain was installed and play around with it for our own collators and validators. I think this issue can be closed now. Thanks for the help!

**Comment by ddorgan** [comment]
@ilhanu glad to hear it's working better. I will recheck all the syntax examples work well on both linux and macos. 

Thanks for your feedback.
